feat: added template structure
MapColonies/ts-script-boilerplate pull request #1
Opened 2021-11-02 13:46 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✔                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-11-04 07:43 UTC, asafMasa requested changes
return the HELM

2021-11-04 08:23 UTC, asafMasa requested changes

2021-11-04 08:23 UTC, asafMasa commented on package.json
> -    "@map-colonies/standard-version-update-helm-version": "^2.0.1",
revert with Helm

2021-11-04 08:23 UTC, asafMasa commented on src/index.ts
> +  app.run(process.argv);
Need to be async

2021-11-10 11:22 UTC, asafMasa approved these changes

2021-11-10 11:22 UTC, asafMasa commented on helm/templates/_helpers.tpl
> -{{/*
check

2021-11-10 11:22 UTC, asafMasa commented on helm/values.yaml
> +  schedule:  '* 0 * * *'
0 0 * * *

2021-11-10 12:20 UTC, asafMasa approved these changes

2021-11-14 09:09 UTC, yossiz16 approved these changes

2021-11-14 10:56 UTC, merged