chore:upgrade packages
MapColonies/ts-script-boilerplate pull request #7
Opened 2023-11-15 13:52 UTC by heliprokupetz14

upgrade by latest packages

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✔                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

2023-11-19 11:47 UTC, netanelC requested changes
Refactor from ts-server-boilerplate to these files:
1. constants - you can remove DEFAULT_SERVER_PORT. It is a script repo and not server. 
2. tracing
3. containerConfig
4. jest.config.js - both integration and unit
5. all config files

2023-11-19 12:48 UTC, netanelC requested changes
Refactor also the files:
1. nvmrc
2. tsconfig.json

2023-11-19 13:01 UTC, netanelC requested changes
1. Refactor properly the containerConfig from server-boilerplate
2. Don't exclude the dumb-init. It is important for long-life script

2023-11-19 13:31 UTC, netanelC approved these changes

2023-11-19 13:51 UTC, netanelC requested changes
The package.json file is not compatible with package.json from ts-server-boilerplate

2023-11-20 08:23 UTC, netanelC approved these changes

2023-12-07 09:56 UTC, shimoncohen requested changes

2023-12-07 09:56 UTC, shimoncohen commented on Dockerfile
> +CMD ["dumb-init", "node", "--max_old_space_size=512", "./index.js"]
Please revert to `ENTRYPOINT` and restore `CMD` command.

2023-12-07 09:56 UTC, shimoncohen commented on src/common/tracing.ts
> +import { ExpressInstrumentation } from '@opentelemetry/instrumentation-express';
Please remove anything related to express.

2023-12-07 09:56 UTC, shimoncohen commented on package.json
> +    "@types/express": "^4.17.17",
Please remove anything related to express.

2023-12-07 09:56 UTC, shimoncohen commented on package.json
> +    "@opentelemetry/instrumentation-express": "0.32.1",
Please remove anything related to express.

2023-12-07 09:56 UTC, shimoncohen commented on package.json
> +    "@opentelemetry/instrumentation-http": "0.35.1",
Please remove anything related to `http` or server.

2023-12-07 09:56 UTC, shimoncohen commented on src/containerConfig.ts
> +  metrics.start();
Please remove anything related to `metrics`, this is for scripts.

2025-01-07 10:19 UTC, closed without merging